#!/usr/bin/env bash

source "$PWD/scripts/common.sh"
source "$PWD/scripts/build_images.sh"

main() {
  export_host_os
  export_dot_env GENERIC_VOLUME_TYPE
  echo "Active host os '${HOST_OS}'"
  build "$@"
  unset GENERIC_VOLUME_TYPE
}

main "$@"