ARG ALPINE_TAG=latest
FROM alpine:latest as toolchain
RUN apk update && \
    apk add --no-cache \
    git \
    build-base \
    cmake \
    automake \
    autoconf \
    pkgconfig \
    libtool \
    coreutils \
    curl \
    unzip \
    gettext-tiny-dev

FROM toolchain as neovim-build
WORKDIR /neovim

ARG STD_XDG_DATA_HOME=/root/.local/share
ARG STD_XDG_CONFIG_HOME=/root/.local/share

ARG NEOVIM_OUTPUT_DIR=/neovim/nvim-install
ARG NEOVIM_GIT_TAG=nightly
ARG NEOVIM_XDG_DATA_HOME=$STD_XDG_DATA_HOME
ARG NEOVIM_XDG_CONFIG_HOME=$STD_XDG_CONFIG_HOME

ENV XDG_DATA_HOME=$NEOVIM_XDG_DATA_HOME
ENV XDG_CONFIG_HOME=$NEOVIM_XDG_CONFIG_HOME

RUN git clone https://github.com/neovim/neovim.git --branch "${NEOVIM_GIT_TAG:?}" .
RUN make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$NEOVIM_OUTPUT_DIR" install
RUN curl -fLo "${XDG_DATA_HOME:?}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

FROM base-developer:$ALPINE_TAG
WORKDIR /projects

ARG STD_XDG_DATA_HOME=/root/.local/share
ARG STD_XDG_CONFIG_HOME=/root/.local/share

ENV XDG_CONFIG_HOME=$STD_XDG_CONFIG_HOME
ENV XDG_DATA_HOME=$STD_XDG_DATA_HOME

COPY --from=neovim-build /neovim/nvim-install /neovim
COPY --from=neovim-build /root/.local/share $XDG_CONFIG_HOME
COPY ./init.vim $XDG_CONFIG_HOME/nvim/

RUN apk update && \
    apk add --no-cache \
        neovim && \
    rm /usr/bin/nvim && ln -s /neovim/bin/nvim /usr/bin/nvim && \
    rm -r /usr/share/nvim && ln -s /neovim/share /usr/share/nvim && \
    ln -s /neovim/lib/parser/c.so /usr/lib/c.so

RUN nvim --headless +PlugInstall +qall

CMD ["nvim","/projects"]