version: "3.8"
## See https://github.com/compose-spec/compose-spec/blob/master/spec.md

## Templates
x-base-developer:
  &default-base-developer
  build:
    context: .
    dockerfile: Dockerfile-base-developer
    args:
      ALPINE_TAG: ${ALPINE_TAG}
      DEV_USER: ${DEV_USER}
      DEV_UID: "${DEV_UID:?'Missing DEV_UID Run DEV_UID=$(id -u) DEV_GID=$(id -g) docker-compose build [options]'}"
      DEV_GID: "${DEV_GID}"
  image: ${DOCKER_REGISTY_AND_PATH:-}base-developer:latest
x-tmux-developer:
  &default-tmux-developer
  image: ${DOCKER_REGISTY_AND_PATH}tmux-developer:latest
  build: 
    context: .
    dockerfile: Dockerfile-tmux
    #target: toolchain
    #target: tmux-build
    args:
      ALPINE_TAG:
      STD_XDG_DATA_HOME:
      STD_XDG_CONFIG_HOME:
      DEV_USER: ${DEV_USER}
      DEV_UID: "${DEV_UID:?'Missing DEV_UID Run DEV_UID=$(id -u) DEV_GID=$(id -g) docker-compose build [options]'}"
      DEV_GID: "${DEV_GID}"
  hostname: tmux-docker
  volumes:
## Working directory there you will have your projects
## Windows
    # - /mnt/c/Users/[USER]/projects:/projects
## Linux
    # - $HOME/projects:/projects
## store tmux session on host machine to be able to restore setup in console.
    - /tmp/resurrect:/home/${DEV_USER}/.tmux/resurrect
x-nvim-developer:
  &default-nvim-developer
  image: ${DOCKER_REGISTY_AND_PATH}nvim-developer:latest
  build:
    context: .
    dockerfile: Dockerfile-nvim
    #target: toolchain
    #target: neovim-build
    args:
      ALPINE_TAG:
      STD_XDG_DATA_HOME:
      STD_XDG_CONFIG_HOME:
#  volumes:
## Working directory there you will have your projects
## Windows
    # - /mnt/c/Users/[USER]/projects:/projects
## Linux
    # - $HOME/projects:/projects

## Services
services:
  base-developer_latest:
    *default-base-developer
  base-developer_specific:
    << : *default-base-developer
    image: ${DOCKER_REGISTY_AND_PATH:-}base-developer:${ALPINE_TAG}
  nvim-developer_latest:
    *default-nvim-developer
  nvim-developer_specific:
    <<  : *default-nvim-developer
    image: ${DOCKER_REGISTY_AND_PATH}nvim-developer:${NEOVIM_DOCKER_TAG}
  tmux-developer_latest:
    *default-tmux-developer
  tmux-developer_specific:
    <<  : *default-tmux-developer
    image: ${DOCKER_REGISTY_AND_PATH}tmux-developer:${TMUX_DOCKER_TAG}
  # vscode-developer:
  #     build:
  #         context: .
  #         dockerfile: Dockerfile-vscode
  # rider-developer:
  #     build:
  #         context: .
  #         dockerfile: Dockerfile-rider