#!/usr/bin/env bash

source "$PWD/scripts/common.sh"

main() {
  export_host_os
  export_dot_env GENERIC_VOLUME_TYPE
  prune_volumes "$@"
  unset GENERIC_VOLUME_TYPE
}

prune_volumes() {
  local all_volumes
  all_volumes=${1:-${ALL_VOLUMES:-no}}
  if [ "$all_volumes" != "no"  ]; then
    unset ALL_VOLUMES
    export GENERIC_VOLUME_TYPE
    version=specific
    GENERIC_VOLUME_TYPE=container
    prune_volumes
    GENERIC_VOLUME_TYPE=localhost
    prune_volumes
    return 0
  elif [[ "${GENERIC_VOLUME_TYPE:?}" == container ]] ||  [[ "${GENERIC_VOLUME_TYPE:?}" == localhost ]]; then
    docker_compose down "${version}" "${GENERIC_VOLUME_TYPE:?}" --volumes
  fi
}

main "$@"
