version: "3.8"
## See https://github.com/compose-spec/compose-spec/blob/master/spec.md

## Templates
x-build-args:
  &default-my-build-args
  ALPINE_TAG: ${ALPINE_TAG}
  DEV_USER: ${DEV_USER}
  DEV_UID: "${DEV_UID:?'Missing DEV_UID Run DEV_UID=$(id -u) DEV_GID=$(id -g) docker-compose build [options]'}"
  DEV_GID: "${DEV_GID}"

x-build-args-xdg_x:
  &default-build-args-xdg-x
  STD_XDG_DATA_HOME:
  STD_XDG_CONFIG_HOME:

x-base-developer:
  &default-base-developer
  build:
    context: .
    dockerfile: base-developer/Dockerfile
    args:
      << : *default-my-build-args
  image: ${GENERIC_DOCKER_REGISTY_AND_PATH:-}base-developer:latest
  environment:
    - HOST_OS

x-tmux-developer:
  &default-tmux-developer
  build: 
    context: .
    dockerfile: ./tmux/Dockerfile
    #target: toolchain
    #target: tmux-build
    args:
      << : *default-my-build-args
      << : *default-build-args-xdg-x
      TMUX_RESURRECT_PROCESSES: "${TMUX_RESURRECT_PROCESSES}"
      TMUX_GIT_BRANCH: "${TMUX_GIT_BRANCH}"
      TMUX_DOCKER_TAG: "${TMUX_DOCKER_TAG}"
  environment:
    - HOST_OS
  hostname: tmux-docker
  ports:
    - '2022:22'

x-nvim-developer:
  &default-nvim-developer
  build:
    context: .
    dockerfile: ./nvim/Dockerfile
    #target: toolchain
    #target: neovim-build
    args:
      << : *default-my-build-args
      << : *default-build-args-xdg-x
      NEOVIM_GIT_BRANCH: "${NEOVIM_GIT_BRANCH}"
      NEOVIM_DOCKER_TAG: "${NEOVIM_DOCKER_TAG}"
  environment:
    - HOST_OS

## Services
services:
  base-developer_latest:
    *default-base-developer
  base-developer_specific:
    << : *default-base-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH:-}base-developer:${ALPINE_TAG}
  nvim-developer_latest:
    << : *default-nvim-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}nvim-developer:latest
  nvim-developer_specific:
    <<  : *default-nvim-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}nvim-developer:${NEOVIM_DOCKER_TAG}
  tmux-developer_latest:
    << : *default-tmux-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}tmux-developer:latest
  tmux-developer_specific:
    <<  : *default-tmux-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}tmux-developer:${TMUX_DOCKER_TAG}
  # vscode-developer:
  #     build:
  #         context: .
  #         dockerfile: ./vscode/Dockerfile
  # rider-developer:
  #     build:
  #         context: .
  #         dockerfile: ./rider/Dockerfile
