version: "3.8"
## See https://github.com/compose-spec/compose-spec/blob/master/spec.md

# Note:
# Mac agent forwarding
# https://docs.docker.com/desktop/mac/networking/#ssh-agent-forwarding
# When using non-root like we are doing we need to hack the ssh agent forwarding
# Inspired by https://gist.github.com/d11wtq/8699521?permalink_comment_id=3878388#gistcomment-3878388

## Templates
x-base-developer:
  &default-base-developer
  environment:
    - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
  volumes:
    - type: bind
      source: /run/host-services/ssh-auth.sock
      target: /run/host-services/ssh-auth.sock
    - /var/run/docker.sock:/var/run/docker.sock
  command: clone ${CLONE_PROJECT_1} ${CLONE_PROJECT_2} ${CLONE_PROJECT_3} ${CLONE_PROJECT_4} ${CLONE_PROJECT_5}

x-tmux-developer:
  &default-tmux-developer
  environment:
    - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
  volumes:
#    - type: bind
#      source: /run/host-services/ssh-auth.sock
#      target: /run/host-services/ssh-auth.sock
    - tmux-projects-container:/projects
    - /var/run/docker.sock:/var/run/docker.sock
    - tmux-ressurect-container:/home/${DEV_USER}/.tmux/resurrect
  command: clone ${CLONE_PROJECT_1} ${CLONE_PROJECT_2} ${CLONE_PROJECT_3} ${CLONE_PROJECT_4} ${CLONE_PROJECT_5}

x-nvim-developer:
  &default-nvim-developer
  environment:
    - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
  volumes:
#    - type: bind
#      source: /run/host-services/ssh-auth.sock
#      target: /run/host-services/ssh-auth.sock
    - /var/run/docker.sock:/var/run/docker.sock
    - nvim-projects-container:/projects:rw
  command: clone ${CLONE_PROJECT_1} ${CLONE_PROJECT_2} ${CLONE_PROJECT_3} ${CLONE_PROJECT_4} ${CLONE_PROJECT_5}

## Services
services:
  base-developer_latest:
    << : *default-base-developer
  base-developer_specific:
    << : *default-base-developer
  nvim-developer_latest:
    << : *default-nvim-developer
  nvim-developer_specific:
    << : *default-nvim-developer
  tmux-developer_latest:
    << : *default-tmux-developer
  tmux-developer_specific:
    << : *default-tmux-developer

volumes:
  base-projects-container: {}
  tmux-projects-container: {}
  tmux-ressurect-container: {}
  nvim-projects-container: {}
