version: "3.8"
## See https://github.com/compose-spec/compose-spec/blob/master/spec.md

## Templates
x-tmux-developer:
  &default-tmux-developer
  environment:
    - SSH_AUTH_SOCK=/agent.sock
  volumes:
    - tmux-projects-localhost:/projects
    - tmux-ressurect-localhost:/home/${DEV_USER}/.tmux/resurrect
    - //var/run/docker.sock:/var/run/docker.sock
    - ${SSH_AUTH_SOCK}:/agent.sock

x-nvim-developer:
  &default-nvim-developer
  environment:
    - SSH_AUTH_SOCK=/agent.sock
  volumes:
    - nvim-projects-localhost:/projects:rw
    - //var/run/docker.sock:/var/run/docker.sock
    - ${SSH_AUTH_SOCK}:/agent.sock

## Services
services:
  nvim-developer_latest:
    << : *default-nvim-developer
  nvim-developer_specific:
    <<  : *default-nvim-developer
  tmux-developer_latest:
    << : *default-tmux-developer
  tmux-developer_specific:
    <<  : *default-tmux-developer

volumes:
## Mapping to localhost
## https://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/
  tmux-projects-localhost:
    driver: local
    driver_opts:
      type: none
      device: ${TMUX_PROJECTS_HOST_PATH}
      o: bind
  tmux-ressurect-localhost:
    driver: local
    driver_opts:
      type: none
      device: ${TMUX_RESURRECT_HOST_PATH}
      o: bind
  nvim-projects-localhost:
    driver: local
    driver_opts:
      type: none
      device: ${NVIM_PROJECTS_HOST_PATH}
      o: bind
