version: "3.8"
## See https://github.com/compose-spec/compose-spec/blob/master/spec.md

## Templates
x-build-args:
  &default-build-args
  ALPINE_TAG: ${ALPINE_TAG}
  DEV_USER: ${DEV_USER}
  DEV_UID: "${DEV_UID:?'Missing DEV_UID Run DEV_UID=$(id -u) DEV_GID=$(id -g) docker-compose build [options]'}"
  DEV_GID: "${DEV_GID}"

x-build-args-xdg-x:
  &default-build-args-xdg-x
  STD_XDG_DATA_HOME:
  STD_XDG_CONFIG_HOME:

x-run-common-props:
  &default-run-common-props
  sysctls:
    # Enable to use ping (Error: "ping: permission denied (are you root?)")
    - "net.ipv4.ping_group_range=0 ${DEV_GID}"

x-base-developer:
  &default-base-developer
  build:
    context: .
    dockerfile: ./base-developer/Dockerfile
    args:
      << : *default-build-args
  environment:
    - HOST_OS
    - RUN_AS_ROOT=${RUN_AS_ROOT}
    - EXECUTE_PROCESS=${BASE_EXECUTE_PROCESS}
    - EXECUTE_PROCESS_EXTRA_ARGS=${BASE_EXECUTE_PROCESS_EXTRA_ARGS}
    - EXECUTE_PROCESS_NO_ARGS=${BASE_EXECUTE_PROCESS_NO_ARGS}
  << : *default-run-common-props
  hostname: base-dev-docker

x-tmux-developer:
  &default-tmux-developer
  build: 
    context: .
    dockerfile: ./tmux/Dockerfile
    #target: toolchain
    #target: tmux-build
    args:
      << : *default-build-args
      << : *default-build-args-xdg-x
      TMUX_RESURRECT_PROCESSES: "${TMUX_RESURRECT_PROCESSES}"
      TMUX_GIT_BRANCH: "${TMUX_GIT_BRANCH}"
      TMUX_DOCKER_TAG: "${TMUX_DOCKER_TAG}"
  hostname: tmux-docker
  ports:
    - '2022:22'
  environment:
    - HOST_OS
    - RUN_AS_ROOT=${RUN_AS_ROOT}
    - TMUX_PLUGIN_MANAGER_PATH
    - EXECUTE_PROCESS=${TMUX_EXECUTE_PROCESS}
    - EXECUTE_PROCESS_EXTRA_ARGS=${TMUX_EXECUTE_PROCESS_EXTRA_ARGS}
    - EXECUTE_PROCESS_NO_ARGS=${TMUX_EXECUTE_PROCESS_NO_ARGS}
  << : *default-run-common-props

x-nvim-developer:
  &default-nvim-developer
  build:
    context: .
    dockerfile: ./nvim/Dockerfile
    #target: toolchain
    #target: neovim-build
    args:
      << : *default-build-args
      << : *default-build-args-xdg-x
      NEOVIM_GIT_BRANCH: "${NEOVIM_GIT_BRANCH}"
  << : *default-run-common-props
  environment:
    - HOST_OS
    - RUN_AS_ROOT=${RUN_AS_ROOT}
    - EXECUTE_PROCESS=nvim
    # - EXECUTE_PROCESS_EXTRA_ARGS=
    # - EXECUTE_PROCESS_NO_ARGS=yes
  hostname: nvim-docker

## Services
services:
  base-developer_latest:
    << : *default-base-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH:-}base-developer:latest
  base-developer_specific:
    << : *default-base-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH:-}base-developer:${ALPINE_TAG}
  nvim-developer_latest:
    << : *default-nvim-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}nvim-developer:latest
  nvim-developer_specific:
    <<  : *default-nvim-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}nvim-developer:${NEOVIM_GIT_BRANCH}
  tmux-developer_latest:
    << : *default-tmux-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}tmux-developer:latest
  tmux-developer_specific:
    <<  : *default-tmux-developer
    image: ${GENERIC_DOCKER_REGISTY_AND_PATH}tmux-developer:${TMUX_DOCKER_TAG}
  # vscode-developer:
  #     build:
  #         context: .
  #         dockerfile: ./vscode/Dockerfile
  # rider-developer:
  #     build:
  #         context: .
  #         dockerfile: ./rider/Dockerfile
