name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build base image
      run: ./build -s base 
    - name: Build nvim image
      run: ./build -s nvim 
    - name: Build tmux image
      run: ./build -s tmux 
