name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build base image
      run: ./build --all-services
    - name: Build base image
      run: ./build --service base --version specific
    - name: Build nvim image
      run: ./build --service nvim --version specific
    - name: Build tmux image
      run: ./build --service tmux --version specific
